name: algrinova
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  material_color_utilities: ^0.12.0
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"  # Optionnel


flutter:
  uses-material-design: true
  assets:
    - assets/images/vecteezy_green-plant-leaves-in-nature_1990614.jpg
    - assets/images/pexels-david-bartus-43782-1166209.jpg
    - assets/images/pexels-mlkbnl-10251392.jpg
    - assets/images/pexels-pixabay-206876.jpg
    - assets/images/pexels-dacapture-13734919.jpg
    - assets/images/frame.png
    - assets/images/blur.png
    - assets/images/blur2.png

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-j7av.ttf
          weight: 700
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 700
